alias ga='git add'
alias gl='git log'
alias gc='git commit'
alias gs='git status'
alias gt='git tag -ma'
alias gpf='git push --follow-tags'
alias gp='git push'
alias gpl='git pull'
alias comp='clang++ -Wall -Wextra -Werror -pedantic -std=c++20 -Wold-style-cast'
alias vim='nvim'
alias nv='nvim'
alias cfe='clang-format-epita'
alias installconfig='vim ~/afs/.confs/install.sh'
alias i3config='vim ~/.config/i3/config'
